In [1]:
import numpy as np
import pandas as pd
import csv
from datetime import datetime
import re
import math
from numpy import load
import pickle

from numpy import savetxt

In [2]:
# data = pd.read_csv("nba2k20-full.csv")
# len(data.columns)

14

In [4]:
XXX = np.loadtxt("data.csv", delimiter=',')
XXX

array([[0.04828572, 0.00102545, 0.05644949, ..., 0.00049779, 0.        ,
        0.        ],
       [0.04811185, 0.00099696, 0.05064144, ..., 0.000496  , 0.        ,
        0.        ],
       [0.04756133, 0.00104536, 0.05439828, ..., 0.00049543, 0.        ,
        0.00049543],
       ...,
       [0.03364148, 0.00102903, 0.0448718 , ..., 0.        , 0.        ,
        0.00049473],
       [0.03362868, 0.00094457, 0.0426293 , ..., 0.        , 0.        ,
        0.        ],
       [0.03314152, 0.00099425, 0.04822833, ..., 0.        , 0.        ,
        0.        ]])

In [10]:
for i in XXX:
    print(round(i.std()))
XXX[0]

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


array([4.82857199e-02, 1.02544931e-03, 5.64494911e-02, 9.97075226e-01,
       1.79204734e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 4.97790927e-04, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.97790927e-04,
       0.00000000e+00, 4.97790927e-04, 0.00000000e+00, 0.00000000e+00])

In [3]:
def clean_data(data):
    data['salary'] = data['salary'].apply(lambda x: int(x[1:]))
    data['jersey'] = data['jersey'].apply(lambda x: int(x[1:]))
    data['b_day'] = data['b_day'].apply(lambda x: datetime.strptime(x, '%m/%d/%y').date())
    data['height'] = data['height'].apply(lambda x: float(x[2+x.find('/'):]))
    data['weight'] = data['weight'].apply(lambda x: float(x[2+x.find('/'):-4]))
    data['draft_round'] = data['draft_round'].apply(lambda x: int(x) if len(x) == 1 else 0)
    data['draft_peak'] = data['draft_peak'].apply(lambda x: int(x) if 1<=len(x)<=2 else 0)
    data['college'] = data['college'].fillna('no education')
    data['team'] = data['team'].fillna('no team')

clean_data(data)

In [4]:
#find age of each player

def age_(birthday):
    today = datetime.strptime(datetime.today().strftime('%Y-%m-%d'), '%Y-%m-%d').date()
    age = today.year - birthday.year
    return int(age)

data['age'] = data['b_day'].apply(lambda x: age_(x))
data.loc[data['country'] != 'USA', 'country'] = 'not USA'
data.loc[data['position'] == 'F-G', 'position'] = 'F'
data.loc[data['position'] == 'G-F', 'position'] = 'F'
data.loc[data['position'] == 'F-C', 'position'] = 'C'
data.loc[data['position'] == 'C-F', 'position'] = 'C'

In [5]:
from sklearn import preprocessing
from scipy import stats

data_dummy = pd.get_dummies(data, columns=['team', 'position','draft_round', 'country'], drop_first= True)
data_dummy = data_dummy.drop(['full_name', 'draft_peak', 'b_day', 'jersey', 'college'], axis = 1)
X, y = data_dummy.drop(['salary'], axis = 1), data_dummy['salary']

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn import preprocessing
from xgboost import XGBRegressor

In [7]:
normalizer = preprocessing.Normalizer().fit(X)
X = normalizer.transform(X)
X = np.array(X)
y = np.array(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
model = model = XGBRegressor( 
    learning_rate=0.04,
    colsample_bytree=0.9, 
    min_child_weight=3.5,
    objective='reg:squarederror',
    max_depth = 2,
    subsample = 0.63,
    eta = 0.1,
    seed=0)

model = model.fit(
    X_train, 
    y_train, 
    eval_metric="rmse", 
    verbose=True)

In [9]:
predictions = model.predict(X_test)
score = model.score(X_test, y_test)

In [10]:
np.sqrt(mean_squared_error(y_test, predictions))

4081931.791464218

In [11]:
savetxt('data.csv', X, delimiter=',')

In [15]:
XXX = np.loadtxt("data.csv", delimiter=',')

In [16]:
XXX

array([[0.04828572, 0.00102545, 0.05644949, ..., 0.00049779, 0.        ,
        0.        ],
       [0.04811185, 0.00099696, 0.05064144, ..., 0.000496  , 0.        ,
        0.        ],
       [0.04756133, 0.00104536, 0.05439828, ..., 0.00049543, 0.        ,
        0.00049543],
       ...,
       [0.03364148, 0.00102903, 0.0448718 , ..., 0.        , 0.        ,
        0.00049473],
       [0.03362868, 0.00094457, 0.0426293 , ..., 0.        , 0.        ,
        0.        ],
       [0.03314152, 0.00099425, 0.04822833, ..., 0.        , 0.        ,
        0.        ]])

In [26]:
# for i in XXX:
#     for j in i:
#         res_std = std()
#     print(i)

np.mean(XXX[0])

0.028056243304671873

In [14]:
model.score(X_test, y_test)

0.8190014009051712